version: '3'

services:
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 4444:4444
    depends_on:
      - db
  db:
    build: ./database
    ports:
      - 5432:5432
    #environment:
      #POSTGRES_USER: postgres
      #POSTGRES_DB: postgres
      #POSTGRES_PASSWORD: password
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
     # - ./database/init.sql:/docker-entrypoint-initdb.d/
