version: '3'

services:
  db:
    image: postgres:12.4
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - "./database/pgdata:/var/lib/postgresql/data"
  server:
    build: ./server
    volumes:
      - "./server:/usr/src/app"
    ports:
      - "${EXPOSED_PORT}:4444"
    depends_on:
      - db
  redis:
    image: redis:6.0.8
    depends_on:
      - server
    ports:
      - 6379:6379


